version: '3.8'

services:
    django:
        build:
            context: .
            dockerfile: ./compose/local/django/Dockerfile
        image: pdf-generator-local-django
        container_name: django
        volumes: 
            - .:/app
        ports:
            - "8000:8000"
        depends_on:
            - postgres
        env_file: 
            - ./.envs/.local/.django
            - ./.envs/.local/.postgres
        command: python manage.py runserver 0.0.0.0:8000

    postgres:
        image: postgres
        container_name: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file: 
            - ./.envs/.local/.postgres

    docs:
        build:
            context: .
            dockerfile: ./compose/local/docs/Dockerfile
        image: pdf-generator-local-docs
        container_name: docs
        env_file:
            - ./.envs/.local/.django
        volumes:
            - ./docs:/docs
            - ./config:/app/config
            - ./pdfgen:/app/pdfgen
        ports:
            - "7000:7000"
        command: make livehtml

volumes:
    postgres_data: