# This is a basic workflow to help you get started with Actions

name: Django Test Runner

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ rjones17-test-actions ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  run_tests:
    if: github.ref == 'refs/heads/rjones17-test-actions'
    name: Run Django Tests
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:13-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: --mount type=tmpfs,destination=/var/lib/postgresql/data --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          ref: 'refs/heads/rjones17-test-actions'
      - name: Set up Python 3.8.6
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.6
      - name: Run Tests
        run: |
          pip install pipenv
          cd pdf-generator-web-app
          pipenv install
          pipenv run python src/manage.py test src/PDFGen/
